server:
  port: 8446
logging:
  file: /java/OCP_LOGS/ocp-ui-api/ocp-ui-api.log
info:
  component: OCP UI API
ribbon:
  ReadTimeout: 50000
  listOfServers: http://localhost:8444
hystrix.command.default.execution.timeout.enabled: false
security:
  oauth2:
    client:
      client-id: ocp-ui-api
ocp:
  ocp-ui-api:
    oauth2:
      authorization-server-endpoint: http://localhost:8080/uaa
      oauth2-client:
        client-id: ocp-ui
        client-secret: changeit
    smart:
      client-ids:
        - c2s_sof_app
        - quippe
        - bhworks
        - 133b3843-5bc1-4293-938d-5debb071943a
---
# updates configuration for docker environment
spring.profiles: docker
ribbon.listOfServers: http://ocp-fis.ocp.com:8444
